### ISSUE TITLE
sirius-ui：/usr/local/bin/docker-entrypoint.sh: exec: line 11: /app/start-dev.sh: not found

### ISSUE THREAD

**Issue by zhoubao0418** [SiriusScan/Sirius#66]
<img width="716" height="347" alt="Image" src="https://github.com/user-attachments/assets/893df3eb-5fbc-498e-b1ea-84a8930a7466" />

**Comment by 0sm0s1z** [comment]
Fixed by UI build error resolution and modern deployment strategy implementation. See commits 0dfde89b and dcee524e for details.

**Comment by nicpenning** [comment]
This seems to still be an issue on Main?

To fix the UI load issue (I am deploying on Windows), I had to fix the `sirius-ui\start-prod.sh` file-> To do this, I opened up the file in VS Code and set CRLF to LF.

**Comment by nicpenning** [comment]
This issue seems to still exist:

<img width="997" height="708" alt="Image" src="https://github.com/user-attachments/assets/f3566125-7d03-46ec-b319-34de0d3a76f0" />

**Comment by 0sm0s1z** [comment]
I'm not sure how you could be getting that now. You may want to confirm that you've destroyed any legacy containers.

**Comment by nicpenning** [comment]
I deleted the Sirius directory and also did
```docker system prune -a```

I will be thorough and search and destroy any other potential lingering containers and builds, thanks for the note!
